blogsite/blog/urls.py
from django.urls import path,include
from . import views
app_name ='blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('users/',views.UserListView.as_view(),name='user_list'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('post/create/',views.PostCreateView,name='post_create'),
    path('post/<pk>/update/',views.PostUpdateView.as_view(),name='post_update'),
    path('post/<pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/<pk>/', views.PostDetailView,name='post_detail'),
    path('comment/<pk>/update/',views.CommentUpdateView.as_view(),name='comment_update'),
    path('comment/<pk>/delete/',views.delete_comment_view,name='comment_delete'),
    path('successsignup/',views.SuccessSignUp,name='sign_up_success'),
    path('user/<pk>/',views.UserDetailView.as_view(),name='user_details'),
    path('block/<pk>',views.BlockUser,name='block_user'),
    path('unblock/<pk>',views.UnblockUser,name='unblock_user'),
    path('post/<pk>/like/',views.like ,name='like'),
    path('post/<pk>/removelike/',views.RemoveLike ,name='remove_like'),


]

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogsite/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.urls import reverse
from PIL import Image
# Create your models here.

class CustomUser(AbstractUser):
    blocked = models.ManyToManyField('CustomUser',related_name='blocked_users',blank=True)
    liked_posts = models.ManyToManyField('Post',related_name='liked_posts',blank=True)

    def __str__(self):
        return self.username

class Post(models.Model):
    post_banner = models.ImageField(upload_to='images/')
    author = models.ForeignKey(CustomUser,related_name='posts',on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    liked_by = models.ManyToManyField('CustomUser',related_name='liked_by',blank=True)
    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)
        if self.post_banner:
            image = Image.open(self.post_banner)
            height, width = image.size
            h,w = height,width
            if height > 450:
                h = 450
            elif width > 800:
                w = 800
            image = image.resize((w,h), Image.ANTIALIAS)
            image.save(self.post_banner.path)
            image.close()


class Comment(models.Model):
    author = models.ForeignKey(CustomUser,related_name='user_comments',on_delete=models.CASCADE)
    post = models.ForeignKey(Post,related_name='post_comments',on_delete=models.CASCADE)
    text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_created']


    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.pk})

    def __str__(self):
        return self.text





class Like(models.Model):
    author = models.ForeignKey(CustomUser,related_name='likedby',on_delete=models.CASCADE)
    post = models.ForeignKey(Post,related_name='postlikes',on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

blogsite/blog/forms.py
from .models import CustomUser,Post,Comment,Like
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1")
        model = CustomUser

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('post_banner','title','text',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'postcontent'}), }



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'})}

blogsite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from blog.forms import PostForm,CommentForm
from .models import CustomUser,Post,Comment,Like
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from django.shortcuts import get_object_or_404,render,redirect,HttpResponseRedirect,HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from django.db.models import Q
from PIL import Image as Image
import base64

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/signup.html'
    
    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'],)
        login(self.request, user)
        return HttpResponseRedirect(reverse('blog:post_list'))

class UserDetailView(DetailView):
    model = CustomUser

class UserListView(ListView):
    model = CustomUser
    context_object_name = 'user_list'
    def get_queryset(self):
        current_user = self.request.user
        if current_user.is_authenticated:
            blocked_users = current_user.blocked.all().values_list('id')
            blocked_by = [user.id for user in CustomUser.objects.all() if current_user in user.blocked.all()]
            return CustomUser.objects.filter(~Q(id__in=blocked_users)).filter(~Q(id__in=blocked_by)).exclude(is_staff=True).exclude(id__exact=current_user.id)
        else:
            return CustomUser.objects.all()
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    def get_queryset(self):
        if self.request.user.is_authenticated:
            current_user = CustomUser.objects.get(username=self.request.user)
            blocked_users = current_user.blocked.all().values_list('id')
            blocked_by = [user for user in CustomUser.objects.all() if current_user in user.blocked.all()]
            return Post.objects.filter(~Q(author__in=blocked_users)).filter(~Q(author__in=blocked_by))

        else:
            return Post.objects.all()
class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

@login_required
def PostCreateView(request):
    post_form = PostForm()
    if request.method=='POST':
        user = CustomUser.objects.get(username=request.user.username)
        post_form = PostForm(request.POST,request.FILES)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.author = user
            new_post.save()
            return redirect(new_post)
        else:
            post_form = PostForm()
    return render(request,
                  'blog/post_form.html',
                  {'form': PostForm()})
                


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

def PostDetailView(request,pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.post_comments
    new_comment = None
    if request.method == 'POST':
        user = CustomUser.objects.get(username=request.user.username)
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = user
            new_comment.save()
            return redirect(post)
    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})





class CommentUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = CommentForm
    model = Comment

def delete_comment_view(request,pk):
    obj = get_object_or_404(Comment,pk=pk)
    post_id = obj.post.pk
    if request.method=='POST':
        obj.delete()
        return HttpResponseRedirect(reverse('blog:post_detail',kwargs={'pk':post_id}))
    return render(request,'blog/delete_comment.html')
        

def SuccessSignUp(request):
    return render(request,'blog/sign_up_success.html')


def BlockUser(request,pk):
    obj = get_object_or_404(CustomUser,pk=pk)
    user_id = obj.pk
    if request.method=='POST':
        user = CustomUser.objects.get(username=request.user)
        user.blocked.add(user_id)
    return HttpResponseRedirect(reverse('blog:user_details',kwargs={'pk':user_id}))


def UnblockUser(request,pk):
    obj = get_object_or_404(CustomUser,pk=pk)
    user_id = obj.pk
    if request.method=='POST':
        user = CustomUser.objects.get(username=request.user)
        user.blocked.remove(user_id)
    return HttpResponseRedirect(reverse('blog:user_details',kwargs={'pk':user_id}))

def like(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post_id = post.pk
    if request.method == 'GET':
        user = CustomUser.objects.get(username=request.user)
        user_id = user.pk
        user.liked_posts.add(post_id)
        post.liked_by.add(user_id)
    return HttpResponseRedirect(reverse("blog:post_detail",kwargs={'pk':post_id}))
def RemoveLike(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post_id = post.pk
    if request.method == 'GET':
        user = CustomUser.objects.get(username=request.user)
        user_id = user.pk
        user.liked_posts.remove(post_id)
        post.liked_by.remove(user_id)
    return HttpResponseRedirect(reverse("blog:post_detail",kwargs={'pk':post_id}))

blogsite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Site</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li class="nav-item active" ><p>Welcome: '{{ user.username }}'</p></li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:user_list' %}">All Users</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/">All Blogs</a>
        </li>
        <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:post_create' %}">Create Post</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'logout' %}?next=/">Logout</a>
            </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:user_list' %}">All Users</a>
        </li>
         <li class="nav-item active">
            <a class="nav-link" href="/">All Blogs</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:signup' %}">Sign Up</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>

    </ul>
    {% endif %}
</div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

blogsite/blog/templates/blog/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Your Comment</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>

<div class="container">
<form method="post">
    <div class="form-group">
        {%csrf_token%}
        {{form.as_p}}

    </div>
    <button class="btn btn-success" type="submit">Save</button>
</form>
</div>

</body>
</html>

blogsite/blog/templates/blog/customuser_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container" >
    <div class="jumbotron">
    <h1>Username: {{ customuser.username }}</h1>
    <h1>Email: {{ customuser.email }} </h1>
        {% ifequal customuser user %}
        {%else%}
        {% if customuser in user.blocked.all %}
        <p style="color:red"> {{ customuser.username }} is in your Block List</p>
        <form method="post" action="{% url 'blog:unblock_user' pk=customuser.pk %}">
        {% csrf_token %}
            <input class="btn btn-warning" type="submit" value="Unblock User">
        </form>
        {% else %}
        <form method="post" action="{% url 'blog:block_user' pk=customuser.pk %}">
        {% csrf_token %}
            <input  class="btn btn-danger" type="submit" value="Block This User">
        </form>
        {% endif %}
        {% endifequal %}

        <div class="form-group">
            Posts By {{customuser.username}}:
            {% for post in customuser.posts.all %}
            <h3>{{forloop.counter}}){{ post.title|safe }}</h3>
            <p class="text-justify"><strong>Published on:</strong> {{ post.date_created|date:"d-m-Y" }}</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

blogsite/blog/templates/blog/customuser_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    {% for person in user_list%}

    <div class="container"  style="border-style:groove">
        <h3>{{ forloop.counter }})<a href="{% url 'blog:user_details' pk=person.id %}">{{ person.username }}</a></h3>
        <div >
            <div>
            <p class="text-justify"><strong>Email:</strong> {{ person.email }}</p>

                </div>
            </div>
    </div>
    {% endfor %}


</div>
{% if user.is_authenticated  and user.blocked.all %}
<div class="jumbotron jumbotron-fluid">
    <h1>Users BLocked By You</h1>
    {% for person in user.blocked.all %}

    <div class="container"  style="border-style:groove">
        <h3>{{ forloop.counter }})<a href="{% url 'blog:user_details' pk=person.id %}">{{ person.username }}</a></h3>
        <div >
            <div>
            <p class="text-justify"><strong>Email:</strong> {{ person.email }}</p>

                </div>
            </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

blogsite/blog/templates/blog/delete_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Comment</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>

<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this Comment ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

</body>
</html>

blogsite/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Comment</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>

<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this Post ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

</body>
</html>

blogsite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{post.title|safe}}</title>
</head>
{% block content %}
<body>
<div class="content container" style="border-style:solid;border-color:black">

    {% if user.is_staff %}
    <span> <a class="btn btn-warning" href="{% url 'blog:post_update' pk=post.pk %}">Edit Post</a></span>
    <span> <a class="btn btn-danger" href="{% url 'blog:post_delete' pk=post.pk %}">Delete Post</a></span>
    {% else %}
{% ifequal post.author.id user.id %}
         <span> <a class="btn btn-warning" href="{% url 'blog:post_update' pk=post.pk %}">Edit Post</a></span>
    <span> <a class="btn btn-danger" href="{% url 'blog:post_delete' pk=post.pk %}">Delete Post</a></span>
    {% endifequal %}
{% endif %}

    <div class="image_wrapper"> <img src="{{ post.post_banner.url }}"> </div>
    <h1> {{ post.title|safe }}</h1>
    <div class="date postdate">Posted On: {{post.date_created}}</div>
    {% if user.is_authenticated %}
    <div class="date postdate">Posted By: <a href="{% url 'blog:user_details' pk=post.author.pk %}"> {{ post.author.username }}</a></div>
    {% if post in user.liked_posts.all %}
    <a href="{%url 'blog:remove_like' pk=post.pk%}" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-thumbs-up"></span> Liked
        </a>
    {% else %}
    <a href="{%url 'blog:like' pk=post.pk%}" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-thumbs-up"></span> Like
        </a>
    {% endif %}
    {% else %}
            <div class="date postdate">Posted By:{{ post.author.username }}</div>
    {% endif %}
    <div style="border-style:ridge">{{ post.text|safe }}</div>
    {% if post.liked_by.count <= 1 %}
    <p>{{post.liked_by.count}} Like</p>
    {% else %}
    <p>{{post.liked_by.count}} Likes</p>
    {% endif %}
    <strong>Comments({{ post.post_comments.all.count }}): </strong>
</div>

    {% for comment in post.post_comments.all %}
    <div class="content container" style="border-style:solid; border-color:black;" >
    <div style="border-style:groove; border-color:red;"><em>{{comment.text|safe}}</em></div>
    <div class="date postdate" >Comment By: {{comment.author}}</div>
    <div class="date postdate" >Comments On: {{comment.date_created}} </div>
    {% if user.is_staff %}
        <a class="btn btn-danger" href="{% url 'blog:comment_delete' pk=comment.pk %}">Delete Comment</a>
    {% else %}
    {% ifequal comment.author.id user.id %}

        <a class="btn btn-warning" href="{% url 'blog:comment_update' pk=comment.pk %}">Edit Your Comment</a>
        <a class="btn btn-danger" href="{% url 'blog:comment_delete' pk=comment.pk %}">Delete Comment</a>

    {% endifequal %}
        {% endif %}
</div>
    {%endfor%}


    <div class="content container" >
    {% if user.is_authenticated %}
    <button class="btn btn-primary" type="submit" id="addcomment" >Add Comment</button>
    <form id="commentform" style="opacity:0" method="post">

        {{comment_form.as_p}}
        {% csrf_token %}

        <button class="btn btn-primary" type="submit">Post Comment</button>
    {% else %}
        <a class="btn btn-success" href="{% url 'login' %}?next={{request.path}}"><button>Login to Add Comment</button></a>
        <a class="likebutton btn btn-primary btn-lg" href="{% url 'login' %}?next={{request.path}}"><button>Login to Like Post</button></a>
    </form>
    {% endif %}

</div>
{% block body %}
{% endblock %}
</body>
<script>
  $("#addcomment").click(function(){
    $("#commentform").css("opacity",'1');
    $("#addcomment").hide()
  });
</script>
<script>
  $("#editbtn").click(function(){
    $("#editcomform").css("opacity",'1');
    $("#editbtn").hide()
  });
</script>
{% endblock %}
</html>

blogsite/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>Create New Post </title>
</head>
<body>
<div class="row form-error">
        <div class="container" id="content">
          <form  method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form.as_p  }}
              <input  class="btn btn-success" type="submit" value="Save">
          </form>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.tiny.cloud/1/udr5kr9l2f75ckq72adu8cw1w0htdv2o01rcuwurwuo9l8ke/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
tinymce.init({
  selector: 'textarea',
  height: 700,
  width:1112,
  automatic_uploads: true,
  plugins: 'image code paste',
  paste_data_images: true,
  toolbar: 'undo redo | link image | code',
  /* enable title field in the Image dialog*/
  image_title: true,
  /* enable automatic uploads of images represented by blob or data URIs*/
  automatic_uploads: true,
  /*
    URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
    images_upload_url: 'postAcceptor.php',
    here we add custom filepicker only to Image dialog
  */
  file_picker_types: 'image',
  /* and here's our custom image picker*/
  file_picker_callback: function (cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');


    /*
      Note: In modern browsers input[type="file"] is functional without
      even adding it to the DOM, but that might not be the case in some older
      or quirky browsers like IE, so you might want to add it to the DOM
      just in case, and visually hide it. And do not forget do remove it
      once you do not need it anymore.
    */

    input.onchange = function () {
      var file = this.files[0];

      var reader = new FileReader();
      reader.onload = function () {
        /*
          Note: Now we need to register the blob in TinyMCEs image blob
          registry. In the next release this part hopefully won't be
          necessary, as we are looking to handle it internally.
        */
        var id = 'blobid' + (new Date()).getTime();
        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        var base64 = reader.result.split(',')[1];
        var blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        /* call the callback and populate the Title field with the file name */
        cb(blobInfo.blobUri(), { title: file.name });
      };
      reader.readAsDataURL(file);
    };

    input.click();
  },
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
});
</script>

</body>

</html>

blogsite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    {% for post in post_list%}
<!--        {% if user  not in post.author.blocked.all %}-->


    <div class="container"  style="border-style:groove">
        <h3>{{ forloop.counter }})<a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title|safe }}</a></h3>
        <div >
            <div>
            <p class="text-justify"><strong>Published By: </strong><a href="{% url 'blog:user_details' post.author.id %}">{{ post.author }}</a></p>
            <p class="text-justify"><strong>Published on:</strong> {{ post.date_created|date:"d-m-Y" }}</p>

                </div>
            </div>
        {% if post.liked_by.count <= 1 %}
    <p>{{post.liked_by.count}} Like</p>
    {% else %}
    <p>{{post.liked_by.count}} Likes</p>
    {% endif %}
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.post_comments.count }}</a>

    </div>
<!--{% endif %}-->
    {% endfor %}
</div>




{% endblock %}

blogsite/blog/templates/blog/sign_up_success.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="Jumbotron">

    <h1> Hurray! Your Registration is Complete!</h1>
    <span><a class="btn btn-primary" href="{% url 'login' %}">Click Here To Login</a></span>
</div>


{% endblock %}

blogsite/blog/templates/blog/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up at Blog Site</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
<div class="jumbotron jumbotron-fluid">
<h1>Sign Up Here!</h1>
<form method="post">
    <div class="form-group">
        <div class="form-control">
    {{ form.as_p }}
    {% csrf_token %}
    <input class="form-control" type="submit" value="SignUp">
</div>
        </div>
</form>
    </div>
</body>
</html>